/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: "#12171F",
				secondary: {
					DEFAULT: "#35917a",
					100: "#30836e",
					200: "#2a7462",
				},
				black: {
					DEFAULT: "#000",
					100: "#1E1E2D",
					200: "#232533",
				},
				gray: {
					100: "#1B232C",
				},
				white: "#f5f5f5",
				opacitywhite: "#1B232C",
				red: "#ea526f",
				blue: "#279af1",
			},
			fontFamily: {
				sfBlack: ["SF-Pro-Display-Black", "sans-serif"],
				sfBlackItalic: ["SF-Pro-Display-BlackItalic", "sans-serif"],
				sfBold: ["SF-Pro-Display-Bold", "sans-serif"],
				sfBoldItalic: ["SF-Pro-Display-BoldItalic", "sans-serif"],
				sfHeavy: ["SF-Pro-Display-Heavy", "sans-serif"],
				sfHeavyItalic: ["SF-Pro-Display-HeavyItalic", "sans-serif"],
				sfLight: ["SF-Pro-Display-Light", "sans-serif"],
				sfLightItalic: ["SF-Pro-Display-LightItalic", "sans-serif"],
				sfMedium: ["SF-Pro-Display-Medium", "sans-serif"],
				sfMediumItalic: ["SF-Pro-Display-MediumItalic", "sans-serif"],
				sf: ["SF-Pro-Display-Regular", "sans-serif"],
				sfItalic: ["SF-Pro-Display-RegularItalic", "sans-serif"],
				sfSemibold: ["SF-Pro-Display-Semibold", "sans-serif"],
				sfSemiboldItalic: ["SF-Pro-Display-SemiboldItalic", "sans-serif"],
				sfThin: ["SF-Pro-Display-Thin", "sans-serif"],
				sfThinItalic: ["SF-Pro-Display-ThinItalic", "sans-serif"],
				sfUltralight: ["SF-Pro-Display-Ultralight", "sans-serif"],
				sfUltralightItalic: ["SF-Pro-Display-UltralightItalic", "sans-serif"],
				sftBlack: ["SF-Pro-Text-Black", "sans-serif"],
				sftBlackItalic: ["SF-Pro-Text-BlackItalic", "sans-serif"],
				sftBold: ["SF-Pro-Text-Bold", "sans-serif"],
				sftBoldItalic: ["SF-Pro-Text-BoldItalic", "sans-serif"],
				sftHeavy: ["SF-Pro-Text-Heavy", "sans-serif"],
				sftHeavyItalic: ["SF-Pro-Text-HeavyItalic", "sans-serif"],
				sftLight: ["SF-Pro-Text-Light", "sans-serif"],
				sftLightItalic: ["SF-Pro-Text-LightItalic", "sans-serif"],
				sftMedium: ["SF-Pro-Text-Medium", "sans-serif"],
				sftMediumItalic: ["SF-Pro-Text-MediumItalic", "sans-serif"],
				sft: ["SF-Pro-Text-Regular", "sans-serif"],
				sftItalic: ["SF-Pro-Text-RegularItalic", "sans-serif"],
				sftSemibold: ["SF-Pro-Text-Semibold", "sans-serif"],
				sftSemiboldItalic: ["SF-Pro-Text-SemiboldItalic", "sans-serif"],
				sftThin: ["SF-Pro-Text-Thin", "sans-serif"],
				sftThinItalic: ["SF-Pro-Text-ThinItalic", "sans-serif"],
				sftUltralight: ["SF-Pro-Text-Ultralight", "sans-serif"],
				sftUltralightItalic: ["SF-Pro-Text-UltralightItalic", "sans-serif"],
			},
		},
	},
	plugins: [],
};
